### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by kisaragi-hiu** [kisaragi-hiu/kisaragi-hiu.com#46]
I want more Mandarin content on the site, but currently that'll become messy really quickly.

Maybe redirect /posts/* to /posts/en (and keep /posts/zh intact)

**Comment by kisaragi-hiu** [comment]
Maybe multiple index streams (#49) can make this easier. Just put different versions in different streams and link between them in the page.

**Comment by kisaragi-hiu** [comment]
Check out `:lang()` for CSS.

```css
.en, .zh-tw, .ja { display: none; }
.en:lang(en), .zh-tw:lang(zh-tw), .ja:lang(ja) {
    display: block;
}
```

https://stackoverflow.com/questions/24034588/static-html-website-bootstrap-multi-language-support

`:lang()` introduction: https://css-tricks.com/almanac/selectors/l/lang/
